# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.hostname = "experimental"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "1024"
  end

  config.vm.provision "shell", path: "provision.sh"

  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/trusty64"
    node1.vm.network "forwarded_port", guest: 2375, host: 12375
    node1.vm.network "forwarded_port", guest: 3375, host: 13375
    node1.vm.network "forwarded_port", guest: 4375, host: 14375

  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/trusty64"
    node2.vm.network "forwarded_port", guest: 2375, host: 22375
    node2.vm.network "forwarded_port", guest: 3375, host: 23375
    node2.vm.network "forwarded_port", guest: 4375, host: 24375
  end

  config.vm.define "node3" do |node3|
    node3.vm.box = "ubuntu/trusty64"
    node3.vm.network "forwarded_port", guest: 2375, host: 32375
    node3.vm.network "forwarded_port", guest: 3375, host: 33375
    node3.vm.network "forwarded_port", guest: 4375, host: 34375
  end
end
